server:
  port: 9527
mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有entity别名类所在包
  type-aliases-package: com.winston.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-zuul-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      # 数据库连接池最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 未添加zuul访问映射时，访问的网址是真是的，例如：http://myzuul.com:9527/microservicecloud-dept/dept/1
zuul:
  routes:
    # 添加了zuul访问映射时，访问的网址变为映射的虚拟网址，例如：http://myzuul.com:9527/mydept/dept/1
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  # 添加ignored-services，表明忽略此访问路径，即不能使用该服务名来访问，转而用映射的虚拟网址来访问
  # 第一种，表示忽略一个真实访问服务名
#  ignored-services: microservicecloud-dept
  # 第二，批处理，所有真实访问服务名都忽略
  ignored-services: "*"
  # 访问前缀，访问网址变成http://myzuul.com:9527/winston/mydept/dept/1
  prefix: /winston